name: Azure Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Update parameters.json
      env:
        SECRET_VALUE: ${{ secrets.VM_PASSWORD }}
      run: |
        jq '.parameters.adminPassword.value = "${SECRET_VALUE}"' -e "./parameters.json" > updated-parameters.json
        mv updated-parameters.json parameters.json


    - name: Deploy ARM Template
      run: az deployment group create --resource-group dev-cert-rg --template-file ./template.json --parameters ./parameters.json --mode Complete
